#*****************************************************************************
#
#  System        : 
#  Module        : 
#  Object Name   : $RCSfile$
#  Revision      : $Revision$
#  Date          : $Date$
#  Author        : $Author$
#  Created By    : Robert Heller
#  Created       : Thu Jun 5 14:31:17 2025
#  Last Modified : <250610.1007>
#
#  Description	
#
#  Notes
#
#  History
#	
#*****************************************************************************
#
#    Copyright (C) 2025  Robert Heller D/B/A Deepwoods Software
#			51 Locke Hill Road
#			Wendell, MA 01379-9728
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# 
#
#*****************************************************************************


import FreeCAD as App
import Part, TechDraw, Mesh, MeshPart, TechDrawGui
from FreeCAD import Base

import os
import sys
sys.path.append(os.path.dirname(__file__))
import time
from PySide.QtCore import QCoreApplication, QEventLoop, QTimer
def execute(loop, ms):
    timer = QTimer()
    timer.setSingleShot(True)
    
    timer.timeout.connect(loop.quit)
    timer.start(ms)
    loop.exec_()

def sleep(ms):
    if not QCoreApplication.instance():
        app = QCoreApplication([])
        execute(app, ms)
    else:
        loop = QEventLoop()
        execute(loop, ms)

from abc import ABCMeta, abstractmethod, abstractproperty

class BirchPanel(metaclass=ABCMeta):
    @property
    def Thickness(self):
        return .125 * 25.4
    @property
    def FingerWidth(self):
        return .5 * 25.4
    @property
    def Color(self):
        return (.8,.8,.8)

class LargeArchWindow(BirchPanel):
    # -263.86346435546875,  .8360995054244995  -- -241.0014190673828 , 0.8360995054244995
    # -263.86346435546875 , 50.67988586425781                  50.67988586425781
    #       -252.43243408203125 , 66.17835235595703
    __archMinorRadius = (-241.0014190673828) - (-252.43243408203125)
    __archMajorRadius = 66.17835235595703-50.67988586425781
    __bottomRectHeight = 50.67988586425781-.8360995054244995
    __bottomRectWidth = (-241.0014190673828) - (-263.86346435546875)
    def __init__(self,origin,side='Front'):
        if not isinstance(origin,Base.Vector):
            raise RuntimeError("origin is not a Vector!")
        self.origin = origin
        if side == 'Front':
            archOrig = origin.add(Base.Vector(self.__archMinorRadius,0,
                                              self.__bottomRectHeight))
            archMajor = archOrig.add(Base.Vector(0,0,self.__archMajorRadius))
            archMinor = archOrig.add(Base.Vector(-self.__archMinorRadius,0,0))
            extrude = Base.Vector(0,self.Thickness,0)
            #print("*** LargeArchWindow.__init__(): archOrig is ",archOrig)
            #print("*** LargeArchWindow.__init__(): archMajor is ",archMajor)
            #print("*** LargeArchWindow.__init__(): archMinor is ",archMinor)
            archEllipse=Part.Ellipse(archMajor,archMinor,archOrig)
            archWire = Part.Wire(archEllipse.toShape())
            archFace = Part.Face(archWire)
            arch     = archFace.extrude(extrude)
            base     = Part.makePlane(self.__bottomRectHeight,
                                      self.__bottomRectWidth,
                                      origin,
                                      Base.Vector(0,1,0)).extrude(extrude)
            self.window = base.fuse(arch)
        elif side == 'Left':
            archOrig = origin.add(Base.Vector(0,
                                              -self.__archMinorRadius,
                                              self.__bottomRectHeight))
            archMajor = archOrig.add(Base.Vector(0,0,self.__archMajorRadius))
            rchMinor = archOrig.add(Base.Vector(0,self.__archMinorRadius,0))
            extrude = Base.Vector(-self.Thickness,0,0)
            archEllipse=Part.Ellipse(archMajor,archMinor,archOrig)
            archWire = Part.Wire(archEllipse.toShape())
            archFace = Part.Face(archWire)
            arch     = archFace.extrude(extrude)
            temp = Base.Vector(0,-self.__bottomRectWidth,0)
            base     = Part.makePlane(self.__bottomRectHeight,
                                      self.__bottomRectWidth,
                                      origin.add(temp),
                                      Base.Vector(-1,0,0)).extrude(extrude)
            self.window = base.fuse(arch)
        elif side == 'Right':
            archOrig = origin.add(Base.Vector(0,
                                              self.__archMinorRadius,
                                              self.__bottomRectHeight))
            archMajor = archOrig.add(Base.Vector(0,0,self.__archMajorRadius))
            rchMinor = archOrig.add(Base.Vector(0,self.__archMinorRadius,0))
            extrude = Base.Vector(self.Thickness,0,0)
            archEllipse=Part.Ellipse(archMajor,archMinor,archOrig)
            archWire = Part.Wire(archEllipse.toShape())
            archFace = Part.Face(archWire)
            arch     = archFace.extrude(extrude)
            base     = Part.makePlane(self.__bottomRectHeight,
                                      self.__bottomRectWidth,
                                      origin,
                                      Base.Vector(1,0,0)).extrude(extrude)
            self.window = base.fuse(arch)
        else:
            raise RuntimeError("unsuported side!")
    def Cut(self,wall):
        return wall.cut(self.window)

class WallPanel(BirchPanel):
    def __init__(self,name,origin,width,height,*,windows=[],side='Front'):
        self.name = name
        if not isinstance(origin,Base.Vector):
            raise RuntimeError("origin is not a Vector!")
        self.origin = origin
        self.side = side
        if side == 'Front':
            #print("*** WallPanel(): width = ",width,", height = ",height)
            extrude = Base.Vector(0,self.Thickness,0)
            panel = Part.makePlane(height,width,origin,Base.Vector(0,1,0)).extrude(extrude)
        elif side == 'Left':
            extrude = Base.Vector(-self.Thickness,0,0)
            panel = Part.makePlane(height,width,
                                   origin.add(Base.Vector(self.Thickness,width,height)),
                                   Base.Vector(-1,0,0)).extrude(extrude)
        elif side == 'Right':
            extrude = Base.Vector(self.Thickness,0,0)
            panel = Part.makePlane(height,width,
                                   origin.add(Base.Vector(0,width,0)),
                                   Base.Vector(1,0,0)).extrude(extrude)
        else:
            raise RuntimeError("unsuported side!")
        self.windows = list()
        for org in windows:
            w = LargeArchWindow(origin.add(org),side)
            panel = w.Cut(panel)
            self.windows.append(w)
        self.wall = panel
    def CutXZfingers(self,*,startx=0,endx=0,zoffset=0,yoffset=0):
        x = startx
        ZNorm=Base.Vector(0,0,1)
        panel = self.wall
        while x <= endx:
            panel = panel.cut(Part.makePlane(self.FingerWidth,\
                                             self.Thickness,\
                                             self.origin.add(Base.Vector(x,yoffset,zoffset)),\
                                             ZNorm).extrude(Base.Vector(0,0,self.Thickness)))
            x += self.FingerWidth*2
        self.wall = panel
    def CutYZfingers(self,*,starty=0,endy=0,zoffset=0,xoffset=0):
        y = starty
        ZNorm=Base.Vector(0,0,1) 
        panel = self.wall
        while y <= endy:
            panel = panel.cut(Part.makePlane(self.Thickness,\
                                             self.FingerWidth,\
                                             self.origin.add(Base.Vector(xoffset,y,zoffset)),\
                                             ZNorm).extrude(Base.Vector(0,0,self.Thickness)))
            y += self.FingerWidth*2
        self.wall = panel
    def CutZYfingers(self,*,startz=0,endz=0,yoffset=0,xoffset=0):
        z = startz
        YNorm=Base.Vector(0,1,0)
        panel = self.wall
        while z <= endz:
            panel = panel.cut(Part.makePlane(self.FingerWidth,\
                                             self.Thickness,\
                                             self.origin.add(Base.Vector(xoffset,yoffset,z)),\
                                             YNorm).extrude(Base.Vector(0,self.Thickness,0)))
            z += self.FingerWidth*2
        self.wall = panel
    def AddPanel(self,*,xoffset=0,yoffset=0,zoffset=0,width=0,height=0):
        if self.side == 'Front':
            extrude = Base.Vector(0,self.Thickness,0)
            panel = Part.makePlane(height,
                                   width,
                                   self.origin.add(Base.Vector(xoffset,
                                                               yoffset,
                                                               zoffset)),
                                   Base.Vector(0,1,0)).extrude(extrude)
            self.wall = self.wall.fuse(panel)
        elif self.side == 'Left':
            extrude = Base.Vector(-self.Thickness,0,0)
            panel = Part.makePlane(height,
                                   width,
                                   self.origin.add(Base.Vector(xoffset+
                                                               self.Thickness,
                                                               yoffset,
                                                               zoffset+
                                                               height)),
                                   Base.Vector(-1,0,0)).extrude(extrude)
            self.wall = self.wall.fuse(panel)
        elif self.side == 'Right':
            extrude = Base.Vector(self.Thickness,0,0)
            panel = Part.makePlane(height,
                                   width,
                                   self.origin.add(Base.Vector(xoffset,
                                                               yoffset,
                                                               zoffset)),
                                   Base.Vector(1,0,0)).extrude(extrude)
            self.wall = self.wall.fuse(panel)
    def CutPanel(self,*,xoffset=0,yoffset=0,zoffset=0,width=0,height=0):
        if self.side == 'Front':
            extrude = Base.Vector(0,self.Thickness,0)
            panel = Part.makePlane(height,
                                   width,
                                   self.origin.add(Base.Vector(xoffset,
                                                               yoffset,
                                                               zoffset)),
                                   Base.Vector(0,1,0)).extrude(extrude)
            self.wall = self.wall.cut(panel)
        elif self.side == 'Left':
            extrude = Base.Vector(-self.Thickness,0,0)
            panel = Part.makePlane(height,
                                   width,
                                   self.origin.add(Base.Vector(xoffset,
                                                               yoffset,
                                                               zoffset)),
                                   Base.Vector(-1,0,0)).extrude(extrude)
            self.wall = self.wall.cut(panel)
        elif self.side == 'Right':
            extrude = Base.Vector(self.Thickness,0,0)
            panel = Part.makePlane(height,
                                   width,
                                   self.origin.add(Base.Vector(xoffset,
                                                               yoffset,
                                                               zoffset)),
                                   Base.Vector(1,0,0)).extrude(extrude)
            self.wall = self.wall.cut(panel)
    def Cut(self,otherWall):
        self.wall = self.wall.cut(otherWall.wall)
    def show(self,doc=None):
        if doc==None:
            doc = App.activeDocument()
        obj = doc.addObject("Part::Feature",self.name)
        obj.Shape = self.wall
        obj.Label=self.name
        obj.ViewObject.ShapeColor=self.Color

class EntryWayAndDoor(object):
    __baseDepth = 183.25379943847656-115.00755310058594
    __baseWidth = 48.76459503173828*2
    __baseHeight = 2.797820568084717-(-18.654172897338867)
    __stepsXOffset = 48.76459503173828-38.98531723022461
    __stepsWidth = 38.98531723022461*2
    __stepsDepths= [183.25379943847656-150.29324340820312,
                    183.25379943847656-158.53338623046875,
                    183.25379943847656-166.77352905273438,
                    183.25379943847656-175.01365661621094]
    __stepsZOffset=[-2.572909116744995-(-18.654172897338867),
                    -7.933324813842773-(-18.654172897338867),
                    -13.293740272521973-(-18.654172897338867),
                    -18.654155731201172-(-18.654172897338867)]
    __frontIndentWidth = (-40.49898910522461)-(-47.277015686035156)
    __frontIndentHeight = (1.3102514743804932)-(-17.166584014892578)
    __frontIndentXOffset = -47.277015686035156-(-48.76459503173828)
    __frontIndentZOffset = (-17.166584014892578)-(-18.654163360595703)
    __frontIndentDepth = 183.253799438476-182.65151977539062
    __frontCoverRoundRadius=.34346008300782
    __frontCoverThickness = .34346008300782*2
    __frontCoverWidth = (-39.0117073059082) - (-49.463340759277344)
    __frontCoverLength = 183.9518737792-115.007431030273
    __columBaseWidth = 16.088188171386718
    __columBaseDepth = 16.08079528808592
    __columBaseHeight = 14.0555922985076906 
    __columCenterY = 134.2124481201172 - 115.00755310058594 + \
                        ((150.29324340820312-134.2124481201172)/2)
    __columBaseCoverThickness = 1.689676284790038
    __columBaseCoverRoundRadius=1.689676284790038/2
    __columBaseCoverWidth=16.933029174804678
    __columBaseCoverDepth=16.92539978027340
    __columBaseRadius = 5.95060729980468
    __columTopRadius  = 5.95060729980468 - 1.61177062988282
    __columHeight = 77.13805389404297 - 18.537721633911133
    __columnC1Radius = (5.95060729980468 - 1.61177062988282)+.39648437500006
    __columnC1Height = 1.00946044921875
    __columnC2Radius = (5.95060729980468 - 1.61177062988282)+.39648437500006 +\
                        .54496765136719
    __columnC2Height = 2.83856964111328
    __columnC3Radius = (5.95060729980468 - 1.61177062988282)+.39648437500006 +\
                        .54496765136719 + 1.96015930175781
    __columnC3Height = 3.67766571044922
    __backWallXOff = -39.0117073059082 - (-48.76459503173828)
    __backWallDepth = 124.75366973876953-115.00755310058594
    __backWallWidth = 38.98501968383789 - (-39.0117073059082)
    __backWallHeight = 16.08079528808592+1.689676284790038+\
                       (77.13805389404297 - 18.537721633911133)+\
                       1.00946044921875+2.83856964111328+3.67766571044922
    __outerDoorWayXOffset = -18.049304962158203 - (-48.76459503173828)
    __outerDoorWayZOffset = 7.670636177062988 - (-18.654172897338867)
    __outerDoorWayMinorRadius = 18
    __outerDoorWayMajorRadius = 24.2
    __outerDoorWayBottomRectHeight = 44.8
    __outerDoorWayBottomRectWidth  = 36
    __outerDoorWayDepth = (124.75366973876953-115.00755310058594)+10
    __doorOuterTunnelXOffset = -25.897098541259766 - (-48.76459503173828)
    __doorOuterTunnelZOffset = 7.670637130737305 - (-18.654172897338867)
    __doorOuterTunnelMinorRadius = 25.897098541259766
    __doorOuterTunnelMajorRadius = 26.862136840820306
    __doorOuterTunnelBottomRectHeight = 52.690696716308594-7.670637130737305
    __doorOuterTunnelBottomRectWidth = 25.897098541259766*2
    __doorTunnelDepth = 115.00755310058594-101.24455261230469
    __doorInnerTunnelXOffset = -21.04060935974121 - (-48.76459503173828)
    __doorInnerTunnelZOffset = 7.670637130737305 - (-18.654172897338867)
    __doorInnerTunnelMinorRadius = 21.04060935974121
    __doorInnerTunnelMajorRadius = 22.0741081237793
    __doorInnerTunnelBottomRectHeight = 52.6026496887207-7.670637130737305
    __doorInnerTunnelBottomRectWidth = 21.04060935974121*2
    __doorThickness = (1.0/16.0)*25.4
    __doorClearance = .5
    __doorHingeBlock1Z = 12.5
    __doorHingeBlock2Z = 44.432012557983395-(12.5*1.5)
    __doorHingeBlockH  = 12.5*.5
    __doorHingeBlockPinR = .5
    __doorPullWidth = (1/8)*25.4
    __doorPullThickness = (1.0/16.0)*25.4 
    __doorPullWireHoleR = (1/64)*25.4
    __entrywayRoofDepth = 162.4363250732422-115.00755310058594
    __entrywayRoofHeight = 88.55018615722656-84.65019226074219
    __entrywayRoofZOffset = 84.65019226074219-(-18.654172897338867)
    __lightCenterX = 0 - (-48.76459503173828)
    __lightCenterY = 115.00755310058594 - \
                        ((149.23240661621094+137.95774841308594)/2)
    __lightBaseRadius = 11.27465820312500/2
    __lightBaseHeight = 84.72457885742188 - 80.42092895507812
    __lightDrop = 80.42092895507812-70.61669921875
    __lightGlobeRadius = (70.61669921875-62.1161003112793)/2
    __lightHoleRadius = (1/16)*25.4
    __lightBaseColor = (139/255, 117/255,   0.0)
    __lightWireColor = (0.25, 0.0, 0.0)
    __lightGlobeColor = (1.0, 1.0, 1.0)
    __entrywayColor=(.7,.7, .7)
    __doorColor=(139/255, 35/255, 35/255)
    def __makeDoors(self):
        doorYOffset = self.__doorTunnelDepth - self.__doorThickness
        doorOrigin = self.origin.add(Base.Vector(
                self.__doorInnerTunnelXOffset+self.__doorClearance,
                doorYOffset,
                self.__doorInnerTunnelZOffset+self.__doorClearance))
        doorArchOrig = doorOrigin.add(Base.Vector(
                self.__doorInnerTunnelMinorRadius-self.__doorClearance,0,
                self.__doorInnerTunnelBottomRectHeight-self.__doorClearance))
        doorMajor = doorArchOrig.add(
                Base.Vector(0,0,self.__doorInnerTunnelMajorRadius-
                                self.__doorClearance))
        doorMinor = doorArchOrig.add(
                Base.Vector((-self.__doorInnerTunnelMinorRadius)+
                            self.__doorClearance,0,0))
        doorExtrude  = Base.Vector(0,self.__doorThickness,0)
        doorEllipse=Part.Ellipse(doorMajor,doorMinor,doorArchOrig)
        doorWire = Part.Wire(doorEllipse.toShape())
        doorFace = Part.Face(doorWire)
        doorArch = doorFace.extrude(doorExtrude)
        doorBase = Part.makePlane(self.__doorInnerTunnelBottomRectHeight-
                                    self.__doorClearance,
                                  self.__doorInnerTunnelBottomRectWidth-
                                    (self.__doorClearance*2),
                                  doorOrigin,
                                  Base.Vector(0,1,0)
                                  ).extrude(doorExtrude)
        bothDoors = doorBase.fuse(doorArch)
        slicer = Part.makePlane(self.__doorInnerTunnelBottomRectHeight*2,
                                (self.__doorInnerTunnelBottomRectWidth/2)+
                                self.__doorClearance,
                                doorOrigin,
                                Base.Vector(0,1,0)
                                ).extrude(doorExtrude)
        rightDoor = bothDoors.cut(slicer)
        rightDoor = self.__addHinges(rightDoor,'Right')
        rightDoor = self.__addPull(rightDoor,'Right')
        self.rightDoor = rightDoor
        slicer = Part.makePlane(self.__doorInnerTunnelBottomRectHeight*2,
                                (self.__doorInnerTunnelBottomRectWidth/2),
                                doorOrigin.add(
                        Base.Vector((self.__doorInnerTunnelBottomRectWidth/2)-
                                    self.__doorClearance,0,0)),
                                Base.Vector(0,1,0)
                                ).extrude(doorExtrude)
        leftDoor = bothDoors.cut(slicer)
        leftDoor = self.__addHinges(leftDoor,'Left')
        leftDoor = self.__addPull(leftDoor,'Left')
        self.leftDoor = leftDoor
    def __addPull(self,door,side):
        doorYOffset = self.__doorTunnelDepth
        if side=='Right':
            pullBlockOrigin = self.origin.add(
               Base.Vector(self.__doorInnerTunnelXOffset+
                           self.__doorClearance*3+
                           ((self.__doorInnerTunnelBottomRectWidth-
                             self.__doorClearance)/2),
                           doorYOffset,
                           self.__doorInnerTunnelZOffset+
                           self.__doorClearance+
                           (self.__doorHingeBlock1Z+
                            self.__doorHingeBlock2Z)/2))
        elif side=='Left':
            pullBlockOrigin = self.origin.add(
               Base.Vector(self.__doorInnerTunnelXOffset+
                           ((self.__doorInnerTunnelBottomRectWidth-
                             self.__doorClearance)/2)-
                           self.__doorPullWidth,
                           doorYOffset,
                           self.__doorInnerTunnelZOffset+
                           self.__doorClearance+
                           (self.__doorHingeBlock1Z+
                            self.__doorHingeBlock2Z)/2))
        else:
            raise RuntimeError("unsupported side: %s"%(side))
        block = Part.makePlane(self.__doorPullWidth,
                               self.__doorPullWidth,
                               pullBlockOrigin
                               ).extrude(
                                    Base.Vector(0,0,self.__doorPullThickness))
        wirehole = Part.Face(Part.Wire(
            Part.makeCircle(self.__doorPullWireHoleR,
                            pullBlockOrigin.add(
                                Base.Vector(self.__doorPullWidth/2,
                                            self.__doorPullWidth/2,
                                            0))))
              ).extrude(Base.Vector(0,0,self.__doorPullThickness))
        block = block.cut(wirehole)        
        return door.fuse(block)
    def __addHinges(self,door,side):
        doorYOffset = self.__doorTunnelDepth - self.__doorThickness
        if side=='Right':
            hingeBlock1Origin = self.origin.add(
                Base.Vector(self.__doorInnerTunnelXOffset+
                            self.__doorInnerTunnelBottomRectWidth-
                            self.__doorClearance,
                            doorYOffset,
                            self.__doorInnerTunnelZOffset+
                            self.__doorClearance+
                            self.__doorHingeBlock1Z))
            hingeBlock2Origin = self.origin.add(
                Base.Vector(self.__doorInnerTunnelXOffset+
                            self.__doorInnerTunnelBottomRectWidth-
                            self.__doorClearance,
                            doorYOffset,
                            self.__doorInnerTunnelZOffset+
                            self.__doorClearance+
                            self.__doorHingeBlock2Z))
            CylinderOffset=Base.Vector(self.__doorThickness*2,
                                       self.__doorThickness/2,0)
            CutOffset     =Base.Vector(0,0,0)
            blockoffset   =Base.Vector(0,0,0)
            pinblockoffset = -self.__doorThickness*2
        elif side=='Left':
            hingeBlock1Origin = self.origin.add(
                Base.Vector(self.__doorInnerTunnelXOffset+
                            self.__doorClearance,
                            doorYOffset,
                            self.__doorInnerTunnelZOffset+
                            self.__doorClearance+
                            self.__doorHingeBlock1Z))
            hingeBlock2Origin = self.origin.add(
                Base.Vector(self.__doorInnerTunnelXOffset+
                            self.__doorClearance,
                            doorYOffset,
                            self.__doorInnerTunnelZOffset+
                            self.__doorClearance+
                            self.__doorHingeBlock2Z))
            CylinderOffset=Base.Vector(-self.__doorThickness*2,
                                       self.__doorThickness/2,0)
            CutOffset     =Base.Vector(-self.__doorThickness*2.5,0,0)
            blockoffset   =Base.Vector(-self.__doorThickness*2,0,0)
            pinblockoffset = 0
        else:
            raise RuntimeError("unsupported side: %s"%(side))
        cut=Part.makePlane(self.__doorThickness*2.5,
                           self.__doorThickness,
                           hingeBlock1Origin.add(CutOffset)).extrude(
                                    Base.Vector(0,0,self.__doorHingeBlockH))
        self.entryway = self.entryway.cut(cut)
        Cylinder = Part.Face(Part.Wire(
                    Part.makeCircle(self.__doorThickness/2,
                                    hingeBlock1Origin.add(CylinderOffset)
                                    ))).extrude(
                                       Base.Vector(0,0,self.__doorHingeBlockH))
        hblock = Part.makePlane(self.__doorThickness*2,
                                self.__doorThickness,
                                hingeBlock1Origin.add(blockoffset)).extrude(
                                        Base.Vector(0,0,self.__doorHingeBlockH))
        door = door.fuse(hblock).fuse(Cylinder)
        pin = Part.Face(Part.Wire(
                Part.makeCircle(self.__doorHingeBlockPinR,
                        hingeBlock1Origin.add(CylinderOffset).add(
                            Base.Vector(0,0,-self.__doorClearance))
                            ))).extrude(
                                  Base.Vector(0,0,self.__doorHingeBlockH+
                                                (2*self.__doorClearance)))
        door = door.fuse(pin)
        pin1= Part.Face(Part.Wire(
                Part.makeCircle(self.__doorHingeBlockPinR*1.2,
                        hingeBlock1Origin.add(CylinderOffset).add(
                            Base.Vector(0,0,-self.__doorClearance))
                            ))).extrude(
                                  Base.Vector(0,0,self.__doorHingeBlockH+
                                                (2*self.__doorClearance)))
        block1=Part.makePlane(self.__doorThickness*2,
                              self.__doorHingeBlockPinR*2.4,
                              hingeBlock1Origin.add(CylinderOffset).add(
                                  Base.Vector(pinblockoffset,
                                              -self.__doorHingeBlockPinR*1.2,
                                              -self.__doorClearance))
                              ).extrude(
                                    Base.Vector(0,0,self.__doorHingeBlockH+
                                                (2*self.__doorClearance)))
        self.entryway = self.entryway.cut(block1.fuse(pin1))
        
        cut=Part.makePlane(self.__doorThickness*2.5,
                           self.__doorThickness,
                           hingeBlock2Origin.add(CutOffset)).extrude(
                                    Base.Vector(0,0,self.__doorHingeBlockH))
        self.entryway = self.entryway.cut(cut)
        Cylinder = Part.Face(Part.Wire(
                    Part.makeCircle(self.__doorThickness/2,
                                    hingeBlock2Origin.add(CylinderOffset)
                                    ))).extrude(
                                       Base.Vector(0,0,self.__doorHingeBlockH))
        hblock = Part.makePlane(self.__doorThickness*2,
                                self.__doorThickness,
                                hingeBlock2Origin.add(blockoffset)).extrude(
                                        Base.Vector(0,0,self.__doorHingeBlockH))
        door = door.fuse(hblock).fuse(Cylinder)
        pin = Part.Face(Part.Wire(
                Part.makeCircle(self.__doorHingeBlockPinR,
                        hingeBlock2Origin.add(CylinderOffset).add(
                            Base.Vector(0,0,-self.__doorClearance))
                            ))).extrude(
                                  Base.Vector(0,0,self.__doorHingeBlockH+
                                                (2*self.__doorClearance)))
        door = door.fuse(pin)
        pin1= Part.Face(Part.Wire(
                Part.makeCircle(self.__doorHingeBlockPinR*1.2,
                        hingeBlock2Origin.add(CylinderOffset).add(
                            Base.Vector(0,0,-self.__doorClearance))
                            ))).extrude(
                                  Base.Vector(0,0,self.__doorHingeBlockH+
                                                (2*self.__doorClearance)))
        block1=Part.makePlane(self.__doorThickness*2,
                              self.__doorHingeBlockPinR*2.4,
                              hingeBlock2Origin.add(CylinderOffset).add(
                                  Base.Vector(pinblockoffset,
                                              -self.__doorHingeBlockPinR*1.2,
                                              -self.__doorClearance))
                              ).extrude(
                                    Base.Vector(0,0,self.__doorHingeBlockH+
                                                (2*self.__doorClearance)))
        self.entryway = self.entryway.cut(block1.fuse(pin1))
                           
        return door
    def __init__(self,name,origin):
        self.name = name
        if not isinstance(origin,Base.Vector):
            raise RuntimeError("origin is not a Vector!")
        self.origin = origin
        base = Part.makePlane(self.__baseWidth,self.__baseDepth,
                              origin.add(Base.Vector(0,-self.__baseDepth,0)),
                              Base.Vector(0,0,1)).extrude(
                                        Base.Vector(0,0,self.__baseHeight))
        for sd,sz in zip(self.__stepsDepths,self.__stepsZOffset):
            stepcut = Part.makePlane(self.__stepsWidth,sd,
                                     origin.add(Base.Vector(
                                                self.__stepsXOffset,
                                                -self.__baseDepth,
                                                sz)),
                                     Base.Vector(0,0,1)).extrude(
                                        Base.Vector(0,0,self.__baseHeight-sz))
            base = base.cut(stepcut)
        frontIndent = Part.makePlane(self.__frontIndentHeight,
                                     self.__frontIndentWidth,
                                     origin.add(Base.Vector(
                                            self.__frontIndentXOffset,
                                            -self.__baseDepth,
                                            self.__frontIndentZOffset)),
                                     Base.Vector(0,1,0)
                         ).extrude(Base.Vector(0,self.__frontIndentDepth,0))
        base = base.cut(frontIndent)
        frontIndent = Part.makePlane(self.__frontIndentHeight,
                                     self.__frontIndentWidth,
                                     origin.add(Base.Vector(
                                            self.__baseWidth -
                                                (self.__frontIndentXOffset+
                                                 self.__frontIndentWidth),
                                            -self.__baseDepth,
                                            self.__frontIndentZOffset)),
                                     Base.Vector(0,1,0)
                         ).extrude(Base.Vector(0,self.__frontIndentDepth,0))
        base = base.cut(frontIndent)
        sidewidth = (self.__baseWidth-self.__stepsWidth)/2
        
        frontCoverOrigin = origin.add(
            Base.Vector(-((self.__frontCoverWidth-sidewidth)/2),
                        -self.__frontCoverLength,
                        self.__baseHeight))
        frontCover = self.__makeFrontCover(frontCoverOrigin)
        base = base.fuse(frontCover)
        frontCoverOrigin = origin.add(
            Base.Vector(self.__baseWidth-sidewidth
                        -((self.__frontCoverWidth-sidewidth)/2),
                        -self.__frontCoverLength,
                        self.__baseHeight))
        frontCover = self.__makeFrontCover(frontCoverOrigin)
        base = base.fuse(frontCover)
        columCenterOrigin = origin.add(Base.Vector(self.__stepsXOffset+
                                                    self.__columBaseWidth/2,
                                                    -self.__columCenterY,
                                                    self.__baseHeight))
        columnWithBase = self.__makecolumnWithBase(columCenterOrigin)
        base = base.fuse(columnWithBase)
        columCenterOrigin = origin.add(Base.Vector(self.__baseWidth-
                                                    self.__stepsXOffset-
                                                    self.__columBaseWidth/2,
                                                    -self.__columCenterY,
                                                    self.__baseHeight))
        columnWithBase = self.__makecolumnWithBase(columCenterOrigin)
        base = base.fuse(columnWithBase)
        backwall = Part.makePlane(self.__backWallWidth,
                                  self.__backWallDepth,
                                  origin.add(Base.Vector(self.__backWallXOff,
                                                         -self.__backWallDepth,
                                                         self.__baseHeight))
                                  ).extrude(Base.Vector(0,0,self.__backWallHeight))
        outerDoorWayTunnelOrigin = origin.add(Base.Vector(
                    self.__outerDoorWayXOffset,0,self.__outerDoorWayZOffset))
        outerDoorWayTunnelArchOrig = outerDoorWayTunnelOrigin.add(
                            Base.Vector(self.__outerDoorWayMinorRadius,0,
                                        self.__outerDoorWayBottomRectHeight))
        outerDoorWayTunnelMajor = outerDoorWayTunnelArchOrig.add(
                            Base.Vector(0,0,self.__outerDoorWayMajorRadius))
        outerDoorWayTunnelMinor = outerDoorWayTunnelArchOrig.add(
                            Base.Vector(-self.__outerDoorWayMinorRadius,0,0))
        outerDoorWayTunnelExtrude = Base.Vector(0,-self.__outerDoorWayDepth,0)
        outerDoorWayTunnelEllipse=Part.Ellipse(
                    outerDoorWayTunnelMajor,
                    outerDoorWayTunnelMinor,
                    outerDoorWayTunnelArchOrig)
        outerDoorWayTunnelWire = Part.Wire(outerDoorWayTunnelEllipse.toShape())
        outerDoorWayTunnelFace = Part.Face(outerDoorWayTunnelWire)
        outerDoorWayTunnelArch = outerDoorWayTunnelFace.extrude(outerDoorWayTunnelExtrude)
        outerDoorWayTunnelBase = Part.makePlane(self.__outerDoorWayBottomRectHeight,
                                                self.__outerDoorWayBottomRectWidth,
                                                outerDoorWayTunnelOrigin,
                                                Base.Vector(0,1,0)
                                                ).extrude(outerDoorWayTunnelExtrude)
                                                
        self.outerDoorWayTunnel =  outerDoorWayTunnelBase.fuse(outerDoorWayTunnelArch)
        backwall = backwall.cut(self.outerDoorWayTunnel)
        
        doorOuterTunnelOrig=origin.add(Base.Vector( 
                self.__doorOuterTunnelXOffset,0,
                self.__doorOuterTunnelZOffset))
        doorOuterTunnelArchOrig = doorOuterTunnelOrig.add(Base.Vector(
                self.__doorOuterTunnelMinorRadius,0,
                self.__doorOuterTunnelBottomRectHeight))
        doorOuterTunnelMajor = doorOuterTunnelArchOrig.add(
                            Base.Vector(0,0,self.__doorOuterTunnelMajorRadius))
        doorOuterTunnelMinor = doorOuterTunnelArchOrig.add(
                            Base.Vector(-self.__doorOuterTunnelMinorRadius,0,0))
        doorOuterTunnelExtrude = Base.Vector(0,self.__doorTunnelDepth,0)
        doorOuterTunnelEllipse=Part.Ellipse(
                    doorOuterTunnelMajor,
                    doorOuterTunnelMinor,
                    doorOuterTunnelArchOrig)
        doorOuterTunnelWire = Part.Wire(doorOuterTunnelEllipse.toShape())
        doorOuterTunnelFace = Part.Face(doorOuterTunnelWire)
        doorOuterTunnelArch = doorOuterTunnelFace.extrude(doorOuterTunnelExtrude)
        doorOuterTunnelBase = Part.makePlane(self.__doorOuterTunnelBottomRectHeight,
                                                self.__doorOuterTunnelBottomRectWidth,
                                                doorOuterTunnelOrig,
                                                Base.Vector(0,1,0)
                                                ).extrude(doorOuterTunnelExtrude)
                                                
        self.doorOuterTunnel =  doorOuterTunnelBase.fuse(doorOuterTunnelArch)

        doorInnerTunnelOrig=origin.add(Base.Vector(
                self.__doorInnerTunnelXOffset,0,
                self.__doorInnerTunnelZOffset))        
        doorInnerTunnelArchOrig = doorInnerTunnelOrig.add(Base.Vector(
                self.__doorInnerTunnelMinorRadius,0,
                self.__doorInnerTunnelBottomRectHeight))
        doorInnerTunnelMajor = doorInnerTunnelArchOrig.add(
                            Base.Vector(0,0,self.__doorInnerTunnelMajorRadius))
        doorInnerTunnelMinor = doorInnerTunnelArchOrig.add(
                            Base.Vector(-self.__doorInnerTunnelMinorRadius,0,0))
        doorInnerTunnelExtrude = Base.Vector(0,self.__doorTunnelDepth,0)
        doorInnerTunnelEllipse=Part.Ellipse(
                    doorInnerTunnelMajor,
                    doorInnerTunnelMinor,
                    doorInnerTunnelArchOrig)
        doorInnerTunnelWire = Part.Wire(doorInnerTunnelEllipse.toShape())
        doorInnerTunnelFace = Part.Face(doorInnerTunnelWire)
        doorInnerTunnelArch = doorInnerTunnelFace.extrude(doorInnerTunnelExtrude)
        doorInnerTunnelBase = Part.makePlane(self.__doorInnerTunnelBottomRectHeight,
                                                self.__doorInnerTunnelBottomRectWidth,
                                                doorInnerTunnelOrig,
                                                Base.Vector(0,1,0)
                                                ).extrude(doorInnerTunnelExtrude)
                                                
        self.doorInnerTunnel =  doorInnerTunnelBase.fuse(doorInnerTunnelArch)
        base = base.fuse(self.doorOuterTunnel.cut(self.doorInnerTunnel))

        base = base.fuse(backwall)
        roof = Part.makePlane(self.__backWallWidth,self.__entrywayRoofDepth,
                              origin.add(
                                    Base.Vector(self.__backWallXOff,
                                                -self.__entrywayRoofDepth, 
                                                self.__entrywayRoofZOffset))
                              ).extrude(Base.Vector(0,0,self.__entrywayRoofHeight))
        base = base.fuse(roof)
        self.entryway = base
        self.__makeDoors()
        lightFixtureOrigin = origin.add(Base.Vector(self.__lightCenterX,
                                                    self.__lightCenterY,
                                                    self.__entrywayRoofZOffset))
        lightWireHole=Part.Face(Part.Wire(
            Part.makeCircle(self.__lightHoleRadius,
                            lightFixtureOrigin))).extrude(
                                Base.Vector(0,0,self.__entrywayRoofHeight))
        self.entryway = self.entryway.cut(lightWireHole)
        lightWireHole=Part.Face(Part.Wire(
            Part.makeCircle(self.__lightHoleRadius,
                            lightFixtureOrigin))).extrude(
                                Base.Vector(0,0,-(self.__lightBaseHeight+
                                                  self.__lightDrop+
                                                  self.__lightGlobeRadius)))
        self.lightBase = Part.makeCone(self.__lightBaseRadius,
                                       0.0,
                                       self.__lightBaseHeight,
                                       lightFixtureOrigin,
                                       Base.Vector(0,0,-1))
        self.lightBase = self.lightBase.cut(lightWireHole)
        self.lightWire = Part.Face(Part.Wire(
            Part.makeCircle(self.__lightHoleRadius/2,
                            lightFixtureOrigin))).extrude(
                                Base.Vector(0,0,-(self.__lightBaseHeight+
                                                  self.__lightDrop+
                                                  self.__lightGlobeRadius)))
        lightGlobeOrigin = lightFixtureOrigin.add(
                Base.Vector(0,0,-(self.__lightBaseHeight+
                                  self.__lightDrop+
                                  self.__lightGlobeRadius)))
        self.lightGlobe = Part.makeSphere(self.__lightGlobeRadius,
                                            lightGlobeOrigin)
    def CutDoorTunnelFromPanel(self,panel):
        return panel.cut(self.doorOuterTunnel)
    def __makecolumnWithBase(self,columCenterOrigin):
        baseOrigin = columCenterOrigin.add(
                Base.Vector(-(self.__columBaseWidth/2),
                            -(self.__columBaseDepth/2),0))
        columnWithBase = Part.makePlane(self.__columBaseWidth,
                                         self.__columBaseDepth,
                                         baseOrigin,
                                         Base.Vector(0,0,1)).extrude(
                                            Base.Vector(0,0,
                                                    self.__columBaseHeight))
        columBaseCover = self.__makeColumnBaseCover(baseOrigin.add(
                                            Base.Vector(-(self.__columBaseCoverWidth-self.__columBaseWidth)/2,
                                                        -(self.__columBaseCoverDepth-self.__columBaseDepth)/2,
                                                        self.__columBaseHeight)))

        columnWithBase = columnWithBase.fuse(columBaseCover)
        column = Part.makeCone(self.__columBaseRadius,
                               self.__columTopRadius,
                               self.__columHeight,
                               columCenterOrigin.add(
                                Base.Vector(0,0,self.__columBaseHeight+
                                                self.__columBaseCoverThickness)))
        columnWithBase = columnWithBase.fuse(column)
        c1 = Part.makeCircle(self.__columnC1Radius,
                             columCenterOrigin.add(
                                Base.Vector(0,0,self.__columBaseHeight+
                                                self.__columBaseCoverThickness+
                                                self.__columHeight)))
        c1 = Part.Face(Part.Wire(c1)).extrude(
                                Base.Vector(0,0,self.__columnC1Height))
        columnWithBase = columnWithBase.fuse(c1)
        c2 = Part.makeCircle(self.__columnC2Radius,
                             columCenterOrigin.add(
                                Base.Vector(0,0,self.__columBaseHeight+
                                                self.__columBaseCoverThickness+
                                                self.__columHeight+
                                                self.__columnC1Height
                                                )))
        c2 = Part.Face(Part.Wire(c2)).extrude(
                            Base.Vector(0,0,self.__columnC2Height))
        columnWithBase = columnWithBase.fuse(c2)
        c3 = Part.makeCircle(self.__columnC3Radius,
                             columCenterOrigin.add(
                                Base.Vector(0,0,self.__columBaseHeight+
                                                self.__columBaseCoverThickness+
                                                self.__columHeight+
                                                self.__columnC1Height+
                                                self.__columnC2Height)))
        c3 = Part.Face(Part.Wire(c3)).extrude(
                                Base.Vector(0,0,self.__columnC3Height))
        columnWithBase = columnWithBase.fuse(c3)
        return columnWithBase
    def __makeColumnBaseCover(self,columBaseCoverOrigin):
        columBaseCover = Part.makePlane(self.__columBaseCoverWidth,
                                         self.__columBaseCoverDepth,
                                         columBaseCoverOrigin,
                                         Base.Vector(0,0,1)).extrude(
                                            Base.Vector(0,0,
                                                    self.__columBaseCoverThickness))
        round1 = Part.makeCircle(self.__columBaseCoverRoundRadius,
                        columBaseCoverOrigin.add(
                             Base.Vector(0,
                                         -self.__columBaseCoverRoundRadius,
                                         self.__columBaseCoverRoundRadius)),
                        Base.Vector(0,-1,0))
        round1 = Part.Face(Part.Wire(round1)
                     ).extrude(Base.Vector(0,self.__columBaseCoverDepth+
                                             (self.__columBaseCoverRoundRadius*2),
                                             0))
        miter1 = Part.makePlane(self.__columBaseCoverThickness,
                                self.__columBaseCoverThickness,
                                columBaseCoverOrigin.add(
                                    Base.Vector(-self.__columBaseCoverRoundRadius,
                                                -self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverThickness)),
                                Base.Vector(1,1,0)).extrude(Base.Vector(
                                    self.__columBaseCoverThickness,
                                    self.__columBaseCoverThickness,0))
        round1 = round1.cut(miter1)
        miter1 = Part.makePlane(self.__columBaseCoverThickness,
                                self.__columBaseCoverThickness,
                                columBaseCoverOrigin.add(
                                    Base.Vector(-self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverDepth+
                                                self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverThickness)),
                                Base.Vector(1,1,0)).extrude(Base.Vector(
                                    self.__columBaseCoverThickness,
                                    self.__columBaseCoverThickness,0))
        round1 = round1.cut(miter1)
        columBaseCover = columBaseCover.fuse(round1)
        round1 = Part.makeCircle(self.__columBaseCoverRoundRadius,
                                 columBaseCoverOrigin.add(
                              Base.Vector(-self.__columBaseCoverRoundRadius,0
                                          ,self.__columBaseCoverRoundRadius)),
                                 Base.Vector(1,0,0))
        round1 = Part.Face(Part.Wire(round1)
                ).extrude(Base.Vector(self.__columBaseCoverWidth + 
                                        self.__columBaseCoverRoundRadius*2,0,0))
        miter1 = Part.makePlane(self.__columBaseCoverThickness,
                                self.__columBaseCoverThickness,
                                columBaseCoverOrigin.add(
                                    Base.Vector(self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverThickness)),
                                 Base.Vector(-1,-1,0)).extrude(Base.Vector(
                                            -self.__columBaseCoverThickness,
                                            -self.__columBaseCoverThickness,0))
        round1 = round1.cut(miter1)
        miter1 = Part.makePlane(self.__columBaseCoverThickness,
                                self.__columBaseCoverThickness,
                                columBaseCoverOrigin.add(
                                    Base.Vector(self.__columBaseCoverWidth+
                                                self.__columBaseCoverRoundRadius,
                                                -self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverThickness)),
                                 Base.Vector(-1,1,0)).extrude(Base.Vector(
                                            -self.__columBaseCoverThickness,
                                            self.__columBaseCoverThickness,0))
        round1 = round1.cut(miter1)
        columBaseCover = columBaseCover.fuse(round1)
        round1 = Part.makeCircle(self.__columBaseCoverRoundRadius,
                                 columBaseCoverOrigin.add(
                              Base.Vector(self.__columBaseCoverWidth,
                                          -self.__columBaseCoverRoundRadius
                                          ,self.__columBaseCoverRoundRadius)),
                                 Base.Vector(0,-1,0))
        round1 = Part.Face(Part.Wire(round1)
                ).extrude(Base.Vector(0,self.__columBaseCoverDepth + 
                                        self.__columBaseCoverThickness,0))
        miter1 = Part.makePlane(self.__columBaseCoverThickness,
                                self.__columBaseCoverThickness,
                                columBaseCoverOrigin.add(
                                    Base.Vector(self.__columBaseCoverWidth+
                                                self.__columBaseCoverRoundRadius,
                                                -self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverThickness)),
                                 Base.Vector(-1,-1,0)).extrude(Base.Vector(
                                            -self.__columBaseCoverThickness,
                                            -self.__columBaseCoverThickness,0))
        round1 = round1.cut(miter1)
        miter1 = Part.makePlane(self.__columBaseCoverThickness,
                                self.__columBaseCoverThickness,
                                columBaseCoverOrigin.add(
                                    Base.Vector(self.__columBaseCoverWidth+
                                                self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverDepth+
                                                self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverThickness)),
                                 Base.Vector(-1,-1,0)).extrude(Base.Vector(
                                            -self.__columBaseCoverThickness,
                                            -self.__columBaseCoverThickness,0))
        round1 = round1.cut(miter1)
        columBaseCover = columBaseCover.fuse(round1)
        round1 = Part.makeCircle(self.__columBaseCoverRoundRadius,
                                 columBaseCoverOrigin.add(
                              Base.Vector(-self.__columBaseCoverRoundRadius,
                                          self.__columBaseCoverDepth,
                                          self.__columBaseCoverRoundRadius)),
                                 Base.Vector(1,0,0))
        round1 = Part.Face(Part.Wire(round1)
                ).extrude(Base.Vector(self.__columBaseCoverWidth + 
                                        self.__columBaseCoverRoundRadius*2,0,0))
        miter1 = Part.makePlane(self.__columBaseCoverThickness,
                                self.__columBaseCoverThickness,
                                columBaseCoverOrigin.add(
                                    Base.Vector(-self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverDepth+
                                                self.__columBaseCoverRoundRadius,
                                                self.__columBaseCoverThickness)),
                                 Base.Vector(1,-1,0)).extrude(Base.Vector(
                                            self.__columBaseCoverThickness,
                                            -self.__columBaseCoverThickness,0))
        round1 = round1.cut(miter1)
        miter1 = Part.makePlane(self.__columBaseCoverThickness,
                                self.__columBaseCoverThickness,
                                columBaseCoverOrigin.add(
                                    Base.Vector(self.__columBaseCoverWidth+
                                                self.__columBaseCoverThickness*1.45,
                                                self.__columBaseCoverDepth,
                                                self.__columBaseCoverThickness)),
                                 Base.Vector(-1,-1,0)).extrude(Base.Vector(
                                            -self.__columBaseCoverThickness,
                                            -self.__columBaseCoverThickness,0))
        round1 = round1.cut(miter1)
        columBaseCover = columBaseCover.fuse(round1)

        return columBaseCover
    def __makeFrontCover(self,frontCoverOrigin):
        frontCover = Part.makePlane(self.__frontCoverWidth,
                                    self.__frontCoverLength,
                                    frontCoverOrigin,
                                    Base.Vector(0,0,1)
                                    ).extrude(Base.Vector(
                                               0,0,self.__frontCoverThickness))
        round1 = Part.makeCircle(self.__frontCoverRoundRadius,
                                 frontCoverOrigin.add(
                              Base.Vector(0,-self.__frontCoverRoundRadius
                                          ,self.__frontCoverRoundRadius)),
                                 Base.Vector(0,-1,0))
        round1 = Part.Face(Part.Wire(round1)
                ).extrude(Base.Vector(0,self.__frontCoverLength + 
                                        self.__frontCoverRoundRadius,0))
        miter1 = Part.makePlane(self.__frontCoverThickness,
                                self.__frontCoverThickness,
                                frontCoverOrigin.add(
                                    Base.Vector(-self.__frontCoverRoundRadius,
                                                -self.__frontCoverRoundRadius,
                                                self.__frontCoverThickness)),
                                 Base.Vector(1,1,0)).extrude(Base.Vector(
                                            self.__frontCoverThickness,
                                            self.__frontCoverThickness,0))
        round1 = round1.cut(miter1)
        frontCover = frontCover.fuse(round1)
        round1 = Part.makeCircle(self.__frontCoverRoundRadius,
                                 frontCoverOrigin.add(
                              Base.Vector(-self.__frontCoverRoundRadius,0
                                          ,self.__frontCoverRoundRadius)),
                                 Base.Vector(1,0,0))
        round1 = Part.Face(Part.Wire(round1)
                ).extrude(Base.Vector(self.__frontCoverWidth + 
                                        self.__frontCoverRoundRadius*2,0,0))
        miter1 = Part.makePlane(self.__frontCoverThickness,
                                self.__frontCoverThickness,
                                frontCoverOrigin.add(
                                    Base.Vector(self.__frontCoverRoundRadius,
                                                self.__frontCoverRoundRadius,
                                                self.__frontCoverThickness)),
                                 Base.Vector(-1,-1,0)).extrude(Base.Vector(
                                            -self.__frontCoverThickness,
                                            -self.__frontCoverThickness,0))
        round1 = round1.cut(miter1)
        miter1 = Part.makePlane(self.__frontCoverThickness,
                                self.__frontCoverThickness,
                                frontCoverOrigin.add(
                                    Base.Vector(self.__frontCoverWidth+
                                                self.__frontCoverRoundRadius,
                                                -self.__frontCoverRoundRadius,
                                                self.__frontCoverThickness)),
                                 Base.Vector(-1,1,0)).extrude(Base.Vector(
                                            -self.__frontCoverThickness,
                                            self.__frontCoverThickness,0))
        round1 = round1.cut(miter1)
        frontCover = frontCover.fuse(round1)
        round1 = Part.makeCircle(self.__frontCoverRoundRadius,
                                 frontCoverOrigin.add(
                              Base.Vector(self.__frontCoverWidth,
                                          -self.__frontCoverRoundRadius
                                          ,self.__frontCoverRoundRadius)),
                                 Base.Vector(0,-1,0))
        round1 = Part.Face(Part.Wire(round1)
                ).extrude(Base.Vector(0,self.__frontCoverLength + 
                                        self.__frontCoverRoundRadius,0))
        miter1 = Part.makePlane(self.__frontCoverThickness,
                                self.__frontCoverThickness,
                                frontCoverOrigin.add(
                                    Base.Vector(self.__frontCoverWidth+
                                                self.__frontCoverRoundRadius,
                                                -self.__frontCoverRoundRadius,
                                                self.__frontCoverThickness)),
                                 Base.Vector(-1,-1,0)).extrude(Base.Vector(
                                            -self.__frontCoverThickness,
                                            -self.__frontCoverThickness,0))
        round1 = round1.cut(miter1)
        frontCover = frontCover.fuse(round1)
        return frontCover
    def show(self,doc=None):
        if doc==None:
            doc = App.activeDocument()
        obj = doc.addObject("Part::Feature",self.name+"_entryway")
        obj.Shape = self.entryway
        obj.Label=self.name+"_entryway"
        obj.ViewObject.ShapeColor=self.__entrywayColor
        obj = doc.addObject("Part::Feature",self.name+"_rightdoor")
        obj.Shape = self.rightDoor
        obj.Label=self.name+"_rightdoor"
        obj.ViewObject.ShapeColor=self.__doorColor
        obj = doc.addObject("Part::Feature",self.name+"_leftdoor")
        obj.Shape = self.leftDoor
        obj.Label=self.name+"_leftdoor"
        obj.ViewObject.ShapeColor=self.__doorColor
        obj = doc.addObject("Part::Feature",self.name+"_lightBase")
        obj.Shape = self.lightBase
        obj.Label=self.name+"_lightBase"
        obj.ViewObject.ShapeColor=self.__lightBaseColor
        obj = doc.addObject("Part::Feature",self.name+"_lightWire")
        obj.Shape = self.lightWire
        obj.Label=self.name+"_lightWire"
        obj.ViewObject.ShapeColor=self.__lightWireColor
        obj = doc.addObject("Part::Feature",self.name+"_lightGlobe")
        obj.Shape = self.lightGlobe
        obj.Label=self.name+"_lightGlobe"
        obj.ViewObject.ShapeColor=self.__lightGlobeColor

class FrontWall(BirchPanel):
    __leftProtrudeOrig = Base.Vector(0,0,0)
    __leftProtrudeWidth = (-213.16818237304688) - (-293.39385986328125)
    __wallHeight = 200.30540466308594-(-18.670610427856445)
    __leftProtrudeWindows = [Base.Vector(-263.86346435546875-(-293.39385986328125),0,
                                          0.8360995054244995-(-18.670610427856445)),
                             Base.Vector(-263.86346435546875-(-293.39385986328125),0,
                                          106.11219024658203-(-18.670610427856445))]
    __protrudeOffsetWidth = (162.4363250732422-115.00755310058594)+(.125*25.4)
    __mainWallWidth = (156.03421020507812-(-213.4210205078125))+(.125*25.4)
    __mainWallWindows=[Base.Vector(-171.88763427734375-(-213.4210205078125)+(.125*25.4),0,
                                   0.8360995054244995-(-18.670610427856445)),
                       Base.Vector(-171.88763427734375-(-213.4210205078125)+(.125*25.4),0,
                                    106.11219024658203-(-18.670610427856445)),
                       Base.Vector(-96.6558609008789-(-213.4210205078125)+(.125*25.4),0,
                                   0.8360995054244995-(-18.670610427856445)),
                       Base.Vector(-96.6558609008789-(-213.4210205078125)+(.125*25.4),0,
                                    106.11219024658203-(-18.670610427856445)),
                       Base.Vector(71.09040832519531-(-213.4210205078125)+(.125*25.4),0,
                                    106.11219024658203-(-18.670610427856445)),
                       Base.Vector(101.06707763671875-(-213.4210205078125)+(.125*25.4),0,
                                    106.11219024658203-(-18.670610427856445))
                      ]
    __entrywayXOffset = -48.76459503173828 - (-213.4203643798828) + 1
    __towerX = -39.011409759521484 - (-291.44384765625)
    __towerY = 0
    __towerZ = 88.55018615722656 - (-18.670610427856445)
    __towerOffsetWidth = 162.4363250732422 - 115.00755310058594
    __towerAdditionalPanelZ = 200.30540466308594 - (-18.670610427856445)
    __towerAdditionalPanelH =  307.5553894042969 - 200.30540466308594
    __towerAdditionalPanelWidth = 115.00755310058594 - 49.40283966064453
    __towerHeight = 307.5553894042969 - 88.55018615722656
    __towerWidth = 38.98531723022461 - (-39.011409759521484)
    __towerWindows = [
                      Base.Vector(-11.444066047668457-(-39.011409759521484),0,
                                  106.11219024658203-88.55018615722656),
                      Base.Vector(-14.261521339416504-(-39.011409759521484),0,
                                  211.02186584472656-88.55018615722656)
                     ]
    def __init__(self,name,origin):
        self.name = name
        if not isinstance(origin,Base.Vector):
            raise RuntimeError("origin is not a Vector!")
        self.origin = origin
        self.leftProtrude = WallPanel(name + "_LeftProtrude",
                             self.origin.add(self.__leftProtrudeOrig),
                             self.__leftProtrudeWidth, 
                             self.__wallHeight,
                             windows=self.__leftProtrudeWindows)
        self.leftProtrude.CutZYfingers(endz=self.__wallHeight)
        self.leftProtrude.CutZYfingers(
                    xoffset=self.__leftProtrudeWidth-self.Thickness,
                    endz=self.__wallHeight)
        protrudeOffsetOrigin = self.origin.add(
                    self.__leftProtrudeOrig.add(Base.Vector(
                                        self.__leftProtrudeWidth-self.Thickness,0,0)))
        self.protrudeOffset = WallPanel(name + "_ProtrudeOffset",
                                        protrudeOffsetOrigin,
                                        self.__protrudeOffsetWidth,
                                        self.__wallHeight,
                                        side='Right')
        self.protrudeOffset.Cut(self.leftProtrude)
        mainWallOrigin = protrudeOffsetOrigin.add(Base.Vector(0,(self.__protrudeOffsetWidth-self.Thickness),0))
        self.mainWall = WallPanel(name + "_MainWall",
                                  mainWallOrigin,
                                  self.__mainWallWidth,
                                  self.__wallHeight,
                                  windows=self.__mainWallWindows)
        self.mainWall.CutZYfingers(endz=self.__wallHeight)
        self.protrudeOffset.Cut(self.mainWall)
        self.mainWall.CutZYfingers(xoffset=self.__mainWallWidth-self.Thickness,
                                   endz=self.__wallHeight)
        entrywayOrigin = mainWallOrigin.add(Base.Vector(self.__entrywayXOffset,
                                                        0,0))
        self.entryway = EntryWayAndDoor(name + "_EntryWay",
                                        entrywayOrigin)
        self.mainWall.wall = self.entryway.CutDoorTunnelFromPanel(self.mainWall.wall)
        towerOffsetOrigin = self.origin.add(
                    Base.Vector(self.__towerX,
                                self.__towerY,
                                self.__towerZ))
        #print("*** FrontWall (constructor): towerOffsetOrigin is %s"%(towerOffsetOrigin))
        #print("*** FrontWall (constructor): self.__towerOffsetWidth is %f"%(self.__towerOffsetWidth))
        self.towerLeftOffset = WallPanel(name + "_TowerLeftOffset",
                                         towerOffsetOrigin,
                                         self.__towerOffsetWidth +
                                         self.Thickness,
                                         self.__towerHeight,
                                         side='Left')
        self.towerLeftOffset.CutZYfingers(endz=self.__towerHeight)
        self.towerLeftOffset.CutZYfingers(yoffset=self.__towerOffsetWidth,
                                          endz=self.__towerHeight)
        self.towerLeftOffset.AddPanel(
            yoffset=self.__towerAdditionalPanelWidth+
                    self.__towerOffsetWidth,
            zoffset=self.__towerAdditionalPanelZ-towerOffsetOrigin.z,
            width=self.__towerAdditionalPanelWidth,
            height=self.__towerAdditionalPanelH)
        self.mainWall.Cut(self.towerLeftOffset)
        self.mainWall.CutPanel(xoffset=(towerOffsetOrigin.x-mainWallOrigin.x)+
                                       self.Thickness,
                               zoffset=self.__towerZ,
                               width=self.__towerWidth-(self.Thickness*2),
                               height=self.__towerHeight)
        towerFrontOrigin = self.origin.add(
                Base.Vector(self.__towerX,
                            self.__towerY,
                            self.__towerZ))
        self.tower = WallPanel(name + "_Tower",
                               towerFrontOrigin,
                               self.__towerWidth,
                               self.__towerHeight,
                               windows=self.__towerWindows,
                               side='Front')
        self.tower.Cut(self.towerLeftOffset)
        towerOffsetOrigin = self.origin.add(
                    Base.Vector(self.__towerX+self.__towerWidth-self.Thickness,
                                self.__towerY,
                                self.__towerZ))
        #print("*** FrontWall (constructor): towerOffsetOrigin is %s"%(towerOffsetOrigin))
        #print("*** FrontWall (constructor): self.__towerOffsetWidth is %f"%(self.__towerOffsetWidth))
        self.towerRightOffset = WallPanel(name + "_TowerRightOffset",
                                         towerOffsetOrigin,
                                         self.__towerOffsetWidth +
                                         self.Thickness,
                                         self.__towerHeight,
                                         side='Right')
        self.towerRightOffset.CutZYfingers(endz=self.__towerHeight)
        self.towerRightOffset.CutZYfingers(yoffset=self.__towerOffsetWidth,
                                          endz=self.__towerHeight)
        self.tower.Cut(self.towerRightOffset)
        self.towerRightOffset.AddPanel(
            yoffset=self.__towerAdditionalPanelWidth+
                    self.__towerOffsetWidth,
            zoffset=self.__towerAdditionalPanelZ-towerOffsetOrigin.z,
            width=self.__towerAdditionalPanelWidth,
            height=self.__towerAdditionalPanelH)
        self.mainWall.Cut(self.towerRightOffset)
        
    def show(self,doc=None):
        if doc==None:
            doc = App.activeDocument()
        self.leftProtrude.show(doc)
        self.protrudeOffset.show(doc)
        self.mainWall.show(doc)
        self.entryway.show(doc)
        self.towerLeftOffset.show(doc)
        self.tower.show(doc)
        self.towerRightOffset.show(doc)
        
if __name__ == '__main__':
    if "AddamsFamilyHouse" in App.listDocuments().keys():
        App.closeDocument("AddamsFamilyHouse")
    doc = App.newDocument("AddamsFamilyHouse")
    frontWall = FrontWall("FrontWall",Base.Vector(0,0,0))
    frontWall.show(doc)
    Gui.activeDocument().activeView().viewFront()
    Gui.SendMsgToActiveView("ViewFit")
